export let BtnConfig = [
    { value: 1, label: '新增' },
    { value: 2, label: '删除' },
    { value: 15, label: '批量删除' },
    { value: 3, label: '修改' },
    { value: 4, label: '详情' },
    { value: 5, label: '停用' },
    { value: 16, label: '批量停用' },
    { value: 6, label: '启用' },
    { value: 17, label: '批量启用' },
    { value: 7, label: '审核' },
    { value: 18, label: '批量审核' },
    { value: 8, label: '反审核' },
    { value: 19, label: '批量反审核' },
    { value: 9, label: '导出' },
    { value: 10, label: '弹窗新增' },
    { value: 11, label: '弹窗删除' },
    { value: 12, label: '弹窗修改' },
    { value: 14, label: '弹窗详情' },
    { value: 13, label: '复制' },
];
export let DATAbASETYPE = [
    { "value": "INT", "label": "INT - 标准整数类型，4 字节" },
    { "value": "SMALLINT", "label": "SMALLINT - 较小的整数类型，2 字节" },
    { "value": "TINYINT", "label": "TINYINT - 更小的整数类型，1 字节" },
    { "value": "BIGINT", "label": "BIGINT - 大整数类型，8 字节" },
    { "value": "BIT", "label": "BIT - 布尔类型，用于存储 0 或 1" },
    { "value": "FLOAT", "label": "FLOAT - 浮点数类型，默认精度为 53 位" },
    { "value": "REAL", "label": "REAL - 单精度浮点数，精度为 24 位" },
    { "value": "DECIMAL(p, s)", "label": "DECIMAL(p, s) - 定点数类型，精度 p 和小数位 s" },
    { "value": "NUMERIC(p, s)", "label": "NUMERIC(p, s) - 与 DECIMAL 相同，精度 p 和小数位 s" },
    { "value": "CHAR(n)", "label": "CHAR(n) - 固定长度字符类型，长度 n，最多 8000 字符" },
    { "value": "VARCHAR(n)", "label": "VARCHAR(n) - 变长字符类型，最大长度 n，最多 8000 字符" },
    { "value": "NCHAR(n)", "label": "NCHAR(n) - 固定长度 Unicode 字符类型，长度 n，最多 4000 字符" },
    { "value": "NVARCHAR(n)", "label": "NVARCHAR(n) - 变长 Unicode 字符类型，最大长度 n，最多 4000 字符" },
    { "value": "TEXT", "label": "TEXT - 过时的文本类型，最多 2^31-1 字节" },
    { "value": "NTEXT", "label": "NTEXT - 过时的 Unicode 文本类型，最多 2^30-1 字符" },
    { "value": "VARCHAR(MAX)", "label": "VARCHAR(MAX) - 变长字符类型，最多 2^31-1 字节" },
    { "value": "NVARCHAR(MAX)", "label": "NVARCHAR(MAX) - 变长 Unicode 字符类型，最多 2^31-1 字符" },
    { "value": "DATE", "label": "DATE - 仅日期，精确到日" },
    { "value": "TIME(p)", "label": "TIME(p) - 仅时间，精度 p (0-7 位小数)" },
    { "value": "DATETIME", "label": "DATETIME - 日期和时间，精度为 3.33 毫秒，范围从 1753 年到 9999 年" },
    { "value": "DATETIME2(p)", "label": "DATETIME2(p) - 改进的日期和时间类型，精度 p (0-7 位小数)，范围从 0001 年到 9999 年" },
    { "value": "TIMESTAMP", "label": "TIMESTAMP - 行版本，用于版本控制，不是实际的日期/时间" },
    { "value": "YEAR", "label": "YEAR - 仅年份，范围从 1900 年到 9999 年" },
    { "value": "UNIQUEIDENTIFIER", "label": "UNIQUEIDENTIFIER - 全球唯一标识符 (GUID)" },
    { "value": "XML", "label": "XML - 用于存储 XML 数据" },
    { "value": "JSON", "label": "JSON - 不直接支持；作为 NVARCHAR 存储并通过 JSON 函数处理" },
    { "value": "BINARY(n)", "label": "BINARY(n) - 固定长度二进制数据，长度 n，最多 8000 字节" },
    { "value": "VARBINARY(n)", "label": "VARBINARY(n) - 变长二进制数据，最大长度 n，最多 8000 字节" },
    { "value": "IMAGE", "label": "IMAGE - 过时的二进制数据类型，最多 2^31-1 字节（建议使用 VARBINARY(MAX) 替代）" },
    { "value": "VARBINARY(MAX)", "label": "VARBINARY(MAX) - 变长二进制数据，最多 2^31-1 字节" }
  ]
  
  